services:
  frontend:
    build: ./front
    ports:
      - 80:3000
    depends_on:
      - backend
      - database
    volumes:
      - ./front/src:/app/src

  backend:
    build: ./back
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3306
      - DB_NAME=database
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./back:/app
      - /app/node_modules

  database:
    image: mysql:8.0.41
    container_name: database
    ports:
      - 33065:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
