services:
  frontend:
    container_name: frontend
    build: ./front
    ports:
      - 80:5173
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
      - database
    volumes:
      - ./front/public:/app/public
      - ./front/src:/app/src

  backend:
    container_name: backend
    build: ./back
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - database
    volumes:
      - ./back/src:/app/src

  database:
    image: mysql:8.0.41
    container_name: database
    ports:
      - 33065:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
